import * as React from 'react';
import Button from '@mui/material/Button';
import CssBaseline from '@mui/material/CssBaseline';
import TextField from '@mui/material/TextField';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import Container from '@mui/material/Container';
import { useDispatch, useSelector } from 'react-redux';
import { UPDATE_TOKEN } from '../../../../RTK/Reducers/Reducers';
import { BackButton } from '../reUseAbles/ReuseAbles';
import { useNavigate } from 'react-router-dom';
import { Divider, Grid } from '@mui/material';
import { useMsal } from '@azure/msal-react';
import { loginRequest } from '../../../../utils/authConfig';

const TokenUpdate = () => {
    const dispatch = useDispatch();
    const navigate = useNavigate();
    const { accessToken } = useSelector(store => store.mainReducer);
    const { instance, accounts } = useMsal();

    const [compare, setCompare] = React.useState(false);
    const [accountToken, setAccountToken] = React.useState(false);

    const handleSubmit = (event) => {
        event.preventDefault();
        const data = new FormData(event.currentTarget);
        dispatch(UPDATE_TOKEN({
            token: data.get('newtoken'),
            notify: true
        }));
    };

    React.useEffect(() => {
        instance
            .acquireTokenSilent({
                ...loginRequest,
                account: accounts[0],
            })
            .then((response) => {
                setAccountToken(response.accessToken)
            }).catch((e) => { console.log("-error ", e) });
        //eslint-disable-next-line
    }, []);


    return (
        <div>
            <Typography variant='h4'>Token Update</Typography>
            <Divider>Actions</Divider>
            <Button variant='outlined' onClick={() => setCompare(!compare)} >{compare ? 'Click to Compare Tokens' : 'Click to Update Token'}</Button>
            <Container component="main" >
                <CssBaseline />
                {
                    compare ?
                        <Box
                            sx={{
                                marginTop: 8,
                                display: 'flex',
                                flexDirection: 'column',
                                alignItems: 'center',
                                justifyContent: 'space-between'
                            }}
                        >



                            <Box component="form" loadingRateList={handleSubmit} id='token' sx={{ mt: 1 }}>
                                <TextField
                                    margin="normal"
                                    required
                                    fullWidth
                                    label="Enter New Token"
                                    name="newtoken"
                                    autoFocus
                                    multiline
                                    minRows={5}
                                    maxRows={5}
                                />
                                <Button
                                    type="submit"
                                    fullWidth
                                    variant="contained"
                                    sx={{ mt: 3, mb: 2 }}
                                >
                                    Update Token
                                </Button>
                            </Box>
                        </Box>
                        :
                        <Grid container spacing={2} alignItems='center' sx={{ marginTop: 3 }} justifyContent={{ xs: 'center', md: 'space-between' }}>
                            <Grid item xs={12} md={6}>
                                <TextField
                                    margin="normal"
                                    required
                                    fullWidth
                                    label="Generated by Account Credential"
                                    name="accounttoken"
                                    autoFocus
                                    defaultValue={accountToken}
                                    multiline
                                    minRows={13}
                                    maxRows={13}
                                />
                            </Grid>
                            <Grid item xs={12} md={6}>
                                <TextField
                                    margin="normal"
                                    required
                                    fullWidth
                                    label="Generated by Postman"
                                    name="newtoken"
                                    defaultValue={accessToken}
                                    autoFocus
                                    multiline
                                    minRows={13}
                                    maxRows={13}
                                />
                            </Grid>
                        </Grid>
                }



            </Container>
            <Box pt={4} pl={2}>
                <BackButton onClick={() => navigate(-1)} />
            </Box>
        </div>
    )
}

export default TokenUpdate;